### ISSUE TITLE
[docs] The puppet-agent package on master-b MUST match the version on master-a

### ISSUE THREAD

**Issue by natemccurdy** [ipcrm/pe_failover#4]
When installing Puppet on master-b before PE is installed on it, care must be taken to install the version of puppet-agent that matches the version installed on master-a.

In PE 2015.3.2, that is puppet-agent version **1.3.5**.

If the version of puppet-agent is different amongst the two masters, then a compile master that uses the master as its MoM will be unable to talk to the other MoM in the case of a fail over. There is a check in the Puppet Enterprise module that verifies if the puppet-agent versions match before allowing a compile master to receive a catalog from the MoM.

**Comment by natemccurdy** [comment]
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while
 evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, This compile
 master has a PE version of '2015.3.2' and an aio puppet-agent version of '1.3.5', while the master of
 masters has version '2015.3.2' and an aio puppet-agent version of '1.3.6'. Please ensure that the PE
 versions are consistent across all Puppet masters by following the LEI upgrade documentation. at
 /opt/puppetlabs/puppet/modules/puppet_enterprise/manifests/profile/master.pp:88:5 on node cm01
```

**Comment by ipcrm** [comment]
Added documentation for this in fd3b516
