### ISSUE TITLE
home directories

### ISSUE THREAD

**Issue by morgajel** [ipcrm/pe_failover#6]
If you have an autofs mounted home, this tries to create /home/pe-transfer and fails. even after figuring out 
`puppet apply -e 'class{pe_failover: rsync_user_home => "/opt/pe-transfer"}; class{pe_failover::active: passive_master => "masterb" }'`

It fails because /opt/pe-transfer and subsequent directories are not auto-created (the now-existing user will have it's home dir changed in /etc/passwd, but it won't create the new home location).

**Comment by ipcrm** [comment]
This line of code is likely responsible for this behavior.
https://github.com/ipcrm/pe_failover/blob/master/manifests/init.pp#L31

Looking back in the code history to try to remember why we aren't managing the home directory.

**Comment by ipcrm** [comment]
Under the covers pe_failover (obviously) is using the native User type in Puppet.  Today, if you take an existing user and update the home directory the puppet user type will NOT create the new home directory, even if managehome is true.  The only time it creates the home directory is if this is a brand new user (basically it uses the useradd -m option).  

[root@masterb modules]# puppet apply -e 'user{"new_user": ensure => present, managehome => true}'
Notice: Compiled catalog for masterb.inf.puppetlabs.demo in environment production in 0.04 seconds
Notice: /Stage[main]/Main/User[new_user]/ensure: created
Notice: Applied catalog in 0.24 seconds

[root@masterb modules]# puppet apply -e 'user{"new_user": ensure => present, home => "/home/test", managehome => true}'
Notice: Compiled catalog for masterb.inf.puppetlabs.demo in environment production in 0.03 seconds
Notice: /Stage[main]/Main/User[new_user]/home: home changed '/home/new_user' to '/home/test'
Notice: Applied catalog in 0.22 seconds

[root@masterb modules]# ll /home/test
ls: cannot access /home/test: No such file or directory

I'm not sure I am going to try to mitigate this within pe_failover, it will require that the home directory be set properly upon first run - or that you handle this situation with additional code outside of pe_failover.
