### ISSUE TITLE
custom home directory unclear/misconfigured in erb.

### ISSUE THREAD

**Issue by morgajel** [ipcrm/pe_failover#8]
$ [root@mastera ~]# puppet apply -e 'class{pe_failover: rsync_user_home => "/opt/pe-transfer"}; class{pe_failover::active: passive_master => “masterb” }'

Notice: Compiled catalog for master1 in environment production in 0.91 seconds
Notice: /Stage[main]/Pe_failover::Active::Classification/Node_group[pe_failover]/classes: classes changed {'pe_failover' => {'rsync_user_home' => '/opt/pe-transfer'}} to '{"pe_failover"=>{}}'
Notice: /Stage[main]/Pe_failover::Active::Classification/Node_group[pe_failover-active]/classes: classes changed {'pe_failover::active' => {'passive_master' => 'masterb'}} to '{"pe_failover::active"=>{}}'
Notice: Applied catalog in 2.01 seconds

$ cat /opt/pe_failover/scripts/sync_certs.sh |grep home
  -e '/usr/bin/ssh -i /home/pe-transfer/.ssh/pe_failover_id_rsa' \

For some reason, the active subclass is not properly setting the rsync_user_home, when when I try to explicitly set it.

puppet apply -e 'class{pe_failover: rsync_user_home => "/opt/pe-transfer"}; class{pe_failover::active: passive_master => "masterb", rsync_user_home => "/opt/pe-transfer" }'
Error: Evaluation Error: Error while evaluating a Resource Statement, Class[Pe_failover::Active]: has no parameter named 'rsync_user_home'  at line 1:60 on node mastera

**Comment by ipcrm** [comment]
https://github.com/ipcrm/pe_failover/blob/master/manifests/params.pp#L3
https://github.com/ipcrm/pe_failover/blob/master/manifests/params.pp#L4

Need to find all the instances of ssh_id being used and see how we can correct the handling shown above.  Based on this code you'd need to override both values to make this work properly, which is not-intuitive at all.

**Comment by ipcrm** [comment]
https://github.com/ipcrm/pe_failover/commit/34fd88138e5aa9f703f59c1dff491ad3a856c541

**Comment by ipcrm** [comment]
Tested with latest commit. This is now working properly with just setting the rsync_user_home override.
